# Streamlit version: 1.7.0


[server]

# Max size, in megabytes, for files uploaded with the file_uploader.
# Default: 200
maxUploadSize = 500


# Enables support for websocket compression.
# Default: true
enableWebsocketCompression = true
